services:
  server:
    build:
      context: "./nazarov/server"
      dockerfile: "./nazarov/server/docker/Dockerfile"
    environment:
      - "APP_HOST=0.0.0.0"
      - "APP_PORT=80"
      - "APP_SQLITE__DB=/tmp/app/storage.db"
    networks:
      - "private"

  client:
    build:
      context: "./nazarov/client"
      dockerfile: "./nazarov/client/docker/Dockerfile"
    environment:
      - "APP_HOST=0.0.0.0"
      - "APP_PORT=80"
      - "APP_API_BASE_URL=http://server:80/api"
    ports:
      - "127.0.0.1:${PORT:-3000}:80"
    networks:
      - "private"

networks:
  private: {}
